#!/bin/sh
# add user-defined startup scripts here

# reg
/sbin/insmod /kmodule/zx_ponreg.ko

#tagparam
/sbin/insmod /kmodule/tagparam_mod.ko


#optical driver
#bob=`sed -n '1p' /proc/capability/opticalinfo  | sed 's/scheme : //g'`
#bobchip=`sed -n '2p' /proc/capability/opticalinfo  | sed 's/vendor : //g'`
#echo "get bob board type:$bob,$bobchip"
#if [ $bob = "6" ]; then
#hexdump /userconfig/longlaser_cfg | grep '0000000 b748 ed12 db90 f624' && /sbin/insmod  /kmodule/GN25L95.ko
#else
#echo "get traditional optical board type"
#fi

# tm sdk
/sbin/insmod /kmodule/tm.ko

ifconfig pon up
ifconfig omci up
# ethdrv
#chizi for ethdrv
/sbin/insmod /kmodule/netdriver.ko
ifconfig sw up



# gponmac sdk
/sbin/insmod /kmodule/zte_gpon.ko

# gpondrv
/sbin/insmod /kmodule/gpondrv.ko

# switch 
/sbin/insmod /kmodule/switch.ko

# optical
/sbin/insmod /kmodule/optical.ko


